/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#eefcf7',
          100: '#d3f8ea',
          200: '#a6efd6',
          300: '#6fe0bd',
          400: '#3ecca2',
          500: '#1eae86',
          600: '#0f8f6f',
          700: '#0d715a',
          800: '#0e5a49',
          900: '#0c493d',
        },
        accent: {
          50: '#f5f3ff',
          100: '#ede9fe',
          200: '#ddd6fe',
          300: '#c4b5fd',
          400: '#a78bfa',
          500: '#8b5cf6',
          600: '#7c3aed',
          700: '#6d28d9',
        },
        surface: {
          DEFAULT: '#ffffff',
          soft: '#f7f9fb',
          muted: '#eef4f1',
          border: '#e1e9e4',
        },
      },
      fontFamily: {
        sans: [
          'Inter',
          'ui-sans-serif',
          'system-ui',
          '-apple-system',
          'Segoe UI',
          'Roboto',
          'Helvetica Neue',
          'Arial',
          'sans-serif',
        ],
      },
      boxShadow: {
        soft: '0 2px 8px rgba(15, 23, 42, 0.06)',
        card: '0 4px 20px rgba(15, 23, 42, 0.08)',
        popover: '0 10px 40px rgba(15, 23, 42, 0.12)',
      },
      keyframes: {
        fadeIn: { '0%': { opacity: 0 }, '100%': { opacity: 1 } },
        slideUp: { '0%': { opacity: 0, transform: 'translateY(8px)' }, '100%': { opacity: 1, transform: 'translateY(0)' } },
        slideInRight: { '0%': { transform: 'translateX(100%)' }, '100%': { transform: 'translateX(0)' } },
        bounceIn: { '0%': { transform: 'scale(0.8)', opacity: 0 }, '100%': { transform: 'scale(1)', opacity: 1 } },
        pulseDot: { '0%, 100%': { opacity: 0.3 }, '50%': { opacity: 1 } },
        shimmer: { '0%': { backgroundPosition: '-1000px 0' }, '100%': { backgroundPosition: '1000px 0' } },
        pulseRing: { '0%': { boxShadow: '0 0 0 0 rgba(16,150,120,0.35)' }, '100%': { boxShadow: '0 0 0 8px rgba(16,150,120,0)' } },
        floatBlob: { '0%, 100%': { transform: 'translate(0,0) scale(1)' }, '50%': { transform: 'translate(10px,-14px) scale(1.05)' } },
      },
      animation: {
        fadeIn: 'fadeIn 0.2s ease-out',
        slideUp: 'slideUp 0.25s ease-out',
        slideInRight: 'slideInRight 0.25s ease-out',
        bounceIn: 'bounceIn 0.2s ease-out',
        pulseDot: 'pulseDot 1.4s infinite ease-in-out',
        shimmer: 'shimmer 1.6s infinite linear',
        pulseRing: 'pulseRing 1.8s infinite ease-out',
        floatBlob: 'floatBlob 8s infinite ease-in-out',
      },
    },
  },
  plugins: [],
};
